build:
	mv npb221/*.class .
	mv npb221/*.java .
	mv npb221/Manifest.txt .
	rm npb221.jar
	javac *.java
	jar cfmv npb221.jar Manifest.txt *.class
	mv *.class npb221
	mv *.java npb221
	mv Manifest.txt npb221
